service: self-service-auth

provider:
  name: aws
  runtime: nodejs20.x

package: 
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    external:
      - 'knex'


functions:
  authorizer:
    handler: src/cmd/functions/authorizer/index.handler
    events:
      - http:
          method: GET
          path: /authorizer