name: Deploy to s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Serverless package
        uses: serverless/github-action@master
        with:
          args: package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        id: upload
        run: |
          aws s3 cp ./serverless/build/self-service-auth-authorizer.zip s3://cloud-burger-deploys/self-service-auth-authorizer.zip
