name: Deploy to s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Serverless
        run: npm i -g serverless@3.39.0

      - name: Install Serverless ESbuild
        run: serverless plugin install -n serverless-esbuild

      - name: Serverless Package
        run: serverless package --package artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: ls
        run: ls

      - name: Upload to S3
        id: upload
        run: |
          aws s3 cp ./serverless/artifacts/authorizer.zip s3://cloud-burger-deploys/authorizer.zip
